---
- name: CHANGED | add to /etc/rc.conf
  sysrc:
    name: new_item
    value: test

- name: OK | no-change of value to /etc/rc.conf
  sysrc:
    name: new_item
    value: test

- name: CHANGED | remove from /etc/rc.conf
  sysrc:
    name: firstboot_pkgs_enable
    state: absent

# Test removing something that shouldn't be in the file
- name: OK | remove non-existent variable from /etc/rc.conf (no-change)
  sysrc:
    name: not_in_this_file
    state: absent

- name: CHANGED | append /etc/rc.conf
  sysrc:
    name: firstboot_pkgs_list
    value: bash
    state: append

- name: CHANGED | subtract /etc/rc.conf
  sysrc:
    name: firstboot_pkgs_list
    value: rsync
    state: subtract

- name: CHANGED | change /etc/rc.conf
  sysrc:
    name: firstboot_freebsd_update_enable
    value: "NO"

- name: CHANGED | creates /tmp/test_sysrc_new
  sysrc:
    name: test
    value: test
    dest: /tmp/test_sysrc_new

- name: CHANGED | updates /tmp/test_sysrc.conf
  sysrc:
    name: test_test
    value: test
    dest: /tmp/test_sysrc.conf

- name: CHANGED | append with delimiter
  sysrc:
    dest: /tmp/test_sysrc.conf
    name: test_delim
    value: t3
    delim: ","
    state: append

- name: CHANGED | subtract with delimiter
  sysrc:
    dest: /tmp/test_sysrc.conf
    name: test_delim
    value: t1
    delim: ";"
    state: subtract

- name: CHANGED | creates file
  sysrc:
    name: test_jail
    value: test
    jail: testjail

- name: OK | update same file with value
  sysrc:
    name: test_jail
    value: test
    jail: testjail

# Issue #11 OID-like variables should fail
- name: OK | oid style names should fail (failed_when)
  register: oid_fail
  failed_when: '"Name may only contain alpha-numeric and underscore characters" not in oid_fail.msg'
  sysrc:
    name: a.b
    value: test
